### ISSUE TITLE
README.md: is libsodium still a pre-requisite

### ISSUE THREAD

**Issue by happybeing** [maidsafe/safe_ffi#15]
From safe_ffi/README.md:

> libsodium is a native dependency for sodiumxoide. Install sodium by following the instructions here.

Is this still true or is this no longer needed due to static linking?

I get the following warning at the end of the build so maybe it _is_ still required (want to be sure though):

```
    note: link against the following native artifacts when linking against this static library
    note: the order and any duplication can be significant on some platforms, and so may need to be preserved
    note: library: rt
    note: library: sodium
    note: library: c
    note: library: m
    note: library: dl
    note: library: pthread
    note: library: gcc_s
    note: library: rt
    note: library: c
    note: library: m
```

Thanks.

**Comment by ustulation** [comment]
So the problem initially was [this](http://stackoverflow.com/questions/32165208/errors-when-linking-libsodium-a-into-a-shared-object/32361029#32361029). Because of that we were forced to use shared object instead of static archive of libsodium while creating a shared object for this crate. Hence all the front end codes ended up requiring 2 shared objects - libsafe_ffi.so **and** libsodium.so. The solution there solved this problem and the current output from my machine is:

```
spandan@spandan-Lenovo-Y50-70~/virtualization/coding/rust-maidsafe/maidsafe-ffi/safe_ffi-1$ ldd target/release/libsafe_ffi.so 
    linux-vdso.so.1 =>  (0x00007fff01bf4000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8be7232000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8be6e6d000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f8be7f9a000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8be6b67000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8be6963000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8be6745000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8be652e000)
spandan@spandan-Lenovo-Y50-70~/virtualization/coding/rust-maidsafe/maidsafe-ffi/safe_ffi-1$ 
```

This shows that there is no need for libsodium.so to be packaged along with libsafe_ffi.so (previously you could see libsodium.so metioned as load dependency there).

What you have pasted is for static archive - libsafe_ffi.a. Static archives don't link against other static archives so if you are using libsafe_ffi.a instead of libsafe_ffi.so, then yes you will have to provide with most of the dependencies mentioned there and probably in that order. You won't be using libsafe_ffi.a in most of the cases though - only for c/c++ executables maybe but even there you can (and should ?) use libsafe_ffi.so. Anyway, in Firefox and non-c/c++ FFI's you will definitely require libsafe_ffi.so.

There can be some effort made in actually opening libsodium.a and libsafe_ffi.a and then combining all object files from both into a new archive with same name libsafe_ffi.a. However right now none of the scenarios we deal in justify this effort.

**Comment by happybeing** [comment]
Thanks for the very useful detail. Shall I (or you) update safe_ffi/README.md to say "libsodium.so is not needed, except in special cirumstances, when using libsafe_ffi.a rather than libsafe_ffi.so, in which case you need to build libsodium as described [here](link)"?

**Comment by ustulation** [comment]
The documentation as far as i can tell is right (your link right now is broken however). libsodium.so is not required under any circumstances, whether you are building libsafe_ffi.so or libsafe_ffi.a. The instructions are to get you libsodium.a (`--enable-shared=no` makes sure you never build libsodium.so). So there is no problem anywhere.

**Comment by happybeing** [comment]
I think we're talking at cross-purposes. My question in the OP (Is this still true or is this no longer needed due to static linking?) refers to the "Pre-requisite" line in the safe_ffi/README.md which tells you to go install libsodium.a. It says:

> libsodium is a native dependency for sodiumxoide. Install sodium by following the instructions here.

I included the linker output in case that was relevant, but I think you are saying: yes, the pre-requisite is needed, whereas I took your response to be, no the pre-requisite is only needed in exceptional circumstances. 

I think I see the difference now, but just want to check because I don't know this stuff very well, still learning :-)

If I've finally got it, good, by all means close this!
